"""
Feature 4: Post-Drive Feedback Mechanism.

After the drive ends, synthesises telemetry, stress markers, and SLM
interventions into a Personalised Feedback Report.

The report is generated by the LLM (Gemini Flash by default; upgrades to
Pro automatically when the drive was particularly stressful).
"""

from __future__ import annotations

import logging
from dataclasses import dataclass, field
from typing import Optional

from thunai.config import PostDriveConfig
from thunai.features.ivis import DriveEvent
from thunai.intelligence.base import BaseLLMProvider, Message

logger = logging.getLogger(__name__)

_FEEDBACK_SYSTEM_PROMPT = """You are an expert driving coach analysing a completed drive.
Use the telemetry summary to write a warm, constructive feedback report.
Structure your response as:
1. Overall Assessment (2 sentences, positive framing)
2. What went well (2–3 bullet points)
3. One gentle suggestion for next time
4. Motivational closing sentence.
Keep the total length under 200 words."""


@dataclass
class DriveSummary:
    """Aggregated metrics from a completed drive session."""

    duration_minutes: float = 0.0
    distance_km: float = 0.0
    average_speed_kmh: float = 0.0
    max_speed_kmh: float = 0.0
    average_stress: float = 0.0
    peak_stress: float = 0.0
    stall_count: int = 0
    ivis_intervention_count: int = 0
    events: list[DriveEvent] = field(default_factory=list)
    route_label: str = "standard"


@dataclass
class FeedbackReport:
    """The generated post-drive feedback for the user."""

    summary: DriveSummary
    report_text: str
    model_used: str
    stress_score_label: str = "low"  # low | moderate | high
    suggestions: list[str] = field(default_factory=list)


class PostDriveAnalyser:
    """
    Generates personalised post-drive feedback using the configured LLM.

    If the drive's average stress exceeds ``use_pro_model_threshold``,
    automatically switches to the higher-quality Pro model for deeper analysis.
    """

    def __init__(
        self,
        config: PostDriveConfig,
        llm_flash: BaseLLMProvider,
        llm_pro: Optional[BaseLLMProvider] = None,
    ) -> None:
        self._config = config
        self._llm_flash = llm_flash
        self._llm_pro = llm_pro

    def analyse(self, summary: DriveSummary) -> FeedbackReport:
        """
        Generate a feedback report from the drive summary.

        Selects Flash for typical drives and Pro for high-stress drives.
        """
        use_pro = (
            summary.average_stress >= self._config.use_pro_model_threshold
            and self._llm_pro is not None
        )
        llm = self._llm_pro if use_pro else self._llm_flash

        prompt = self._build_prompt(summary)
        messages = [
            Message(role="system", content=_FEEDBACK_SYSTEM_PROMPT),
            Message(role="user", content=prompt),
        ]

        response = llm.generate(messages)

        stress_label = (
            "high" if summary.average_stress >= 0.7
            else "moderate" if summary.average_stress >= 0.4
            else "low"
        )

        report = FeedbackReport(
            summary=summary,
            report_text=response.text,
            model_used=response.model,
            stress_score_label=stress_label,
        )
        logger.info(
            "Post-drive report generated (model=%s, stress=%s, tokens=%d).",
            response.model,
            stress_label,
            response.output_tokens,
        )
        return report

    def generate_synthetic_scenarios(self, summary: DriveSummary) -> list[str]:
        """
        Use the LLM to generate synthetic "What-If" scenarios based on
        difficult moments in the drive (for SLM fine-tuning).
        """
        high_stress_events = [e for e in summary.events if e.stress_delta >= 0.2]
        if not high_stress_events:
            return []

        event_desc = "; ".join(e.description for e in high_stress_events[:3])
        prompt = (
            f"A driver experienced the following stressful events: {event_desc}. "
            "Generate 5 realistic 'What-If' driving scenarios involving similar situations "
            "on Indian roads. Format each as a single sentence starting with 'Scenario:'."
        )
        messages = [Message(role="user", content=prompt)]
        response = self._llm_flash.generate(messages, max_tokens=512)

        scenarios = [
            line.strip()
            for line in response.text.splitlines()
            if line.strip().startswith("Scenario:")
        ]
        logger.info("Generated %d synthetic scenarios.", len(scenarios))
        return scenarios

    @staticmethod
    def _build_prompt(summary: DriveSummary) -> str:
        event_types = ", ".join({e.event_type for e in summary.events}) or "none"
        return (
            f"Drive duration: {summary.duration_minutes:.0f} minutes | "
            f"Distance: {summary.distance_km:.1f} km | "
            f"Average speed: {summary.average_speed_kmh:.0f} km/h | "
            f"Average stress score: {summary.average_stress:.2f} (0–1 scale) | "
            f"Peak stress: {summary.peak_stress:.2f} | "
            f"Engine stalls: {summary.stall_count} | "
            f"IVIS interventions: {summary.ivis_intervention_count} | "
            f"Events detected: {event_types} | "
            f"Route type: {summary.route_label}. "
            "Please provide personalised feedback."
        )
